version: '3.9'

services:
  go-app:
    container_name: go-app
    build: .
    environment: 
      DATABASE_URL: "host=go_db user=postgres password=password dbname=postgres sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - go_db
    env_file:
      - .env

  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
