"CREATE DATABASE IF NOT EXISTS `system_books`"

`CREATE TABLE IF NOT EXISTS books (
	book_id     INT AUTO_INCREMENT PRIMARY KEY,
	name 		VARCHAR(255) NOT NULL,
	author 		VARCHAR(255) NOT NULL,
	pages 		INT NOT NULL,
	description VARCHAR(255) NOT NULL,
	published	DATE,
	image		VARCHAR(255) NOT NULL,
	status		TINYINT(1) DEFAULT 1)`

`CREATE TABLE IF NOT EXISTS users (
    id 		INT AUTO_INCREMENT PRIMARY KEY,
    first_name 	VARCHAR(255) NOT NULL,
    last_name 	VARCHAR(255) NOT NULL,
    email 	VARCHAR(255) NOT NULL,
    password 	VARCHAR(255) NOT NULL,
    country 	VARCHAR(255) NOT NULL)`

`CREATE TABLE IF NOT EXISTS contact (
	id 			INT AUTO_INCREMENT PRIMARY KEY,
	name 		VARCHAR(255) NOT NULL,
	email 		VARCHAR(255) NOT NULL,
	message 	VARCHAR(255) NOT NULL
	)`
